// Aqua Glass - accent chip contrast.
//
// GNOME pairs accent-coloured backgrounds with white text (`-st-accent-fg-color`
// is hard-coded to #ffffff in st-theme-context.c). Several of the stock accents
// do not reach WCAG AA against white:
//
//     blue   #3584e4 -> 3.77:1   FAIL
//     teal   #2190a4 -> 3.90:1   FAIL
//     green  #3a944a -> 3.79:1   FAIL   (values computed by color.js)
//
// Adaptive text deliberately does NOT recolour anything inside these chips -
// they paint their own filled background and overriding the label would put
// black text on accent blue. But that leaves a real contrast failure sitting
// on our glass, so we fix it at the source: darken the chip background until
// its own white label passes, and emit a small stylesheet that says so.

import Gio from 'gi://Gio';
import GLib from 'gi://GLib';
import St from 'gi://St';

import * as Log from './logger.js';
import {parse, toHex, adjustForContrast, contrastRatio, ACCENT_FG} from './color.js';
import {accentColorHex} from './compat.js';

/** Selectors whose background is the accent colour. */
const ACCENT_SELECTORS = [
    '.quick-toggle:checked',
    '.quick-menu-toggle .quick-toggle:checked',
    '.quick-toggle:checked:hover',
    '.quick-slider .slider',
    '.button:default',
    '.message-list-clear-button:checked',
    '.calendar-today:selected',
    '.events-button .event-time:selected',
];

export class AccentFix {
    constructor() {
        this._file = null;
        this._loaded = false;
        this._report = null;
    }

    get report() {
        return this._report;
    }

    /**
     * Compute the corrected accent and, if a correction is needed, load a
     * generated stylesheet that applies it.
     *
     * @param {string} cacheDir where to write the generated CSS
     * @returns {object|null} a description of what was done
     */
    apply(cacheDir) {
        this.revert();

        const hex = accentColorHex();
        const accent = parse(hex);
        const fg = parse(ACCENT_FG);
        if (!accent || !fg)
            return null;

        const before = contrastRatio(accent, fg);
        const result = adjustForContrast(accent, fg, 4.5);

        this._report = {
            accent: hex,
            ratioBefore: Math.round(before * 100) / 100,
            ratioAfter: Math.round(result.ratio * 100) / 100,
            corrected: result.adjusted,
            correctedColour: result.adjusted ? toHex(result.color) : hex,
        };

        if (!result.adjusted) {
            Log.debug(`accent ${hex} already passes AA (${this._report.ratioBefore}:1)`);
            return this._report;
        }

        const corrected = toHex(result.color);
        const css = this._buildCss(corrected);

        try {
            GLib.mkdir_with_parents(cacheDir, 0o755);
            const path = GLib.build_filenamev([cacheDir, 'aqua-glass-accent.css']);
            GLib.file_set_contents(path, css);

            this._file = Gio.File.new_for_path(path);
            const theme = St.ThemeContext.get_for_stage(global.stage).get_theme();
            theme.load_stylesheet(this._file);
            this._loaded = true;

            Log.info(`accent ${hex} was ${this._report.ratioBefore}:1 against white; ` +
                     `using ${corrected} at ${this._report.ratioAfter}:1`);
        } catch (e) {
            Log.error(e, 'loading accent stylesheet');
            this._file = null;
            this._loaded = false;
        }

        return this._report;
    }

    _buildCss(colour) {
        const rules = ACCENT_SELECTORS.join(',\n');
        return [
            '/* Generated by Aqua Glass. Do not edit - regenerated on enable. */',
            `${rules} {`,
            `    background-color: ${colour};`,
            `    color: ${ACCENT_FG};`,
            '}',
            '',
        ].join('\n');
    }

    /** Unload the generated stylesheet. */
    revert() {
        if (this._loaded && this._file) {
            try {
                const theme = St.ThemeContext.get_for_stage(global.stage).get_theme();
                theme.unload_stylesheet(this._file);
            } catch (e) {
                Log.error(e, 'unloading accent stylesheet');
            }
        }
        this._loaded = false;
        this._file = null;
    }
}
